FROM nginx:1.18.0

COPY ./dist /usr/share/nginx/html
#COPY ./node_modules /usr/share/nginx/html/node_modules
COPY ./nginx-config/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx-config/nginx-legpromrf-docker.conf /etc/nginx/conf.d/legpromrf.conf
